using Godot;

namespace MpFoundation.Ui.Design;

/// <summary>
/// Writes <c>resources/UITheme.tres</c> from <see cref="UiThemeFactory"/>.
///
/// <para><b>What this file is for, and what it is not.</b> The running game does not read the
/// <c>.tres</c> — <see cref="UiThemeService"/> builds the theme from tokens and hangs it on the
/// root window, which takes precedence over the project's fallback theme. The exported resource
/// exists so the <i>editor</i> previews scenes in something close to the shipped look, and so
/// <c>project.godot</c>'s <c>gui/theme/custom</c> still points at something real.</para>
///
/// <para><b>This is how audit finding 10 dies.</b> The old <c>tools/BuildTheme.gd</c> had
/// drifted from its own output on at least six values, so nobody dared run it, so screens grew
/// their own constants instead. Here the exported file is generated by the same code the game
/// runs, so "the generator disagrees with the theme" is not a state this project can reach:
/// re-exporting is always safe, and never re-exporting is also safe.</para>
///
/// <code>godot --headless --path . -- --build-ui-theme</code>
/// </summary>
public static class UiThemeExport
{
    public const string OutPath = "res://resources/UITheme.tres";

    /// <summary>Exports the front-of-house temperature — that is what the editor is previewing
    /// when it opens a menu scene. Returns a process exit code.</summary>
    public static int Run()
    {
        Theme theme = UiThemeFactory.Build(UiThemeService.FrontEnd);
        Error err = ResourceSaver.Save(theme, OutPath);
        if (err != Error.Ok)
        {
            GD.PrintErr($"[ui-theme] export failed: {err}");
            return 1;
        }

        GD.Print($"[ui-theme] wrote {OutPath} at {UiThemeService.FrontEnd} temperature");
        GD.Print("[ui-theme] THEME_SAVED " + OutPath);
        return 0;
    }
}
